name: Auto-merge dependency updates

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run security scan
        run: |
          pip install safety
          safety check --json

      - name: Run tests
        run: |
          pytest tests/ -v --cov=app --cov-report=term-missing

      - name: Run linting
        run: |
          flake8 app/
          black --check app/

      - name: Enable auto-merge for Dependabot PRs
        if: success()
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
