name: Auto-merge dependency updates

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run security scan
        run: |
          # Run Semgrep with auto-config (detects language and applies relevant rules)
          semgrep --config=auto --error --json --output=semgrep-results.json app/
          # Additional security-focused ruleset for thorough scanning
          semgrep --config=p/security-audit --error app/

      - name: Run tests
        run: |
          pytest tests/ -v --cov=app --cov-report=term-missing

      - name: Run linting
        run: |
          flake8 app/
          black --check app/

      - name: Enable auto-merge for Dependabot PRs
        if: success()
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
